### ISSUE TITLE
YAML with tabSize=4 always shows errors for lists

### ISSUE THREAD

**Issue by igorakkerman** [oderwat/vscode-indent-rainbow#196]
When using a `tabSize` of `4` (or any value `>=3`), in a YAML file with dashed lists, either the dashed or the non-dashed lines will show errors:
```yaml
my-list:
    - my-item-prop1: my value 1  # no error here, multiple of 4
      my-item-prop2: my value 2  # shows error here, not a multiple of 4
```
```yaml
my-list:
  - my-item-prop1: my value 1    # shows error here, not a multiple of 4
    my-item-prop2: my value 2    # no error here, multiple of 4
```
At least for the first example, I can't think of an ignore pattern that would work.
